version: '3'
services:
  site:
    image: magento/php:7.0.33
    volumes:
      - ../magento:/var/www/html
    environment:
      - "XDEBUG_REMOTE_HOST=192.168.0.5"
      - "XDEBUG_REMOTE_PORT=9000"
    ports:
      - 80:80
      - 443:443
  db:
    image: magento/mariadb:10.5.5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

  phpmyadmin:
    image: phpmyadmin:5
    restart: always
    ports:
      - 7700:80
    environment:
      - PMA_ARBITRARY=1




